"""
Django settings for mysite project.

Real-time Team Chat & Notification Platform
Django Channels + WebSocket + PostgreSQL + Redis

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# Core Settings
# =============================================================================

SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-b^^e9w%5_vfi=l&y&omfql0zs_2)cz)g$tk3&l&r)6c&%p^nap',
)

DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# =============================================================================
# Application Definition
# =============================================================================

INSTALLED_APPS = [
    # Daphne MUST be before django.contrib.staticfiles to override runserver
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'channels',
    'rest_framework',

    # Project apps
    'accounts',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise phải nằm ngay sau SecurityMiddleware để serve static ổn định
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # static/ nằm trong DIRS để `{% include "icons.svg" %}` inline được
        # sprite (currentColor không kế thừa qua <use href> ngoài tài liệu).
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'static'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mysite.context_processors.asset_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# =============================================================================
# ASGI Configuration (Django Channels + Daphne)
# =============================================================================

ASGI_APPLICATION = 'mysite.asgi.application'


# =============================================================================
# Channel Layers (Redis — see ADR-002)
# =============================================================================

USE_INMEMORY_CHANNEL = os.environ.get('USE_INMEMORY_CHANNEL', 'False').lower() in ('true', '1', 'yes')

if USE_INMEMORY_CHANNEL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [os.environ.get('REDIS_URL', 'redis://localhost:6379/0')],
            },
        },
    }


# =============================================================================
# Database (PostgreSQL — see ADR-005)
# =============================================================================

# Parse DATABASE_URL or fall back to individual components
USE_SQLITE = os.environ.get('USE_SQLITE', 'False').lower() in ('true', '1', 'yes')
DATABASE_URL = '' if USE_SQLITE else os.environ.get('DATABASE_URL', '')

if DATABASE_URL:
    # Parse postgres://user:password@host:port/dbname
    import re
    match = re.match(
        r'postgres(?:ql)?://(?P<user>[^:]+):(?P<password>[^@]+)@(?P<host>[^:]+):(?P<port>\d+)/(?P<name>.+)',
        DATABASE_URL,
    )
    if match:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': match.group('name'),
                'USER': match.group('user'),
                'PASSWORD': match.group('password'),
                'HOST': match.group('host'),
                'PORT': match.group('port'),
                'CONN_MAX_AGE': 60,
                'OPTIONS': {
                    'connect_timeout': 5,
                },
            },
        }
    else:
        raise ValueError(f'Invalid DATABASE_URL format: {DATABASE_URL}')
else:
    # Fallback to SQLite for quick local testing without Docker
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
    }


# =============================================================================
# Password Validation
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =============================================================================
# Internationalization
# =============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_TZ = True


# =============================================================================
# Static Files
# =============================================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


def _asset_version():
    """Mốc thời gian sửa mới nhất của static/css + static/js."""
    latest = 0
    for folder in ('css', 'js'):
        directory = BASE_DIR / 'static' / folder
        if not directory.is_dir():
            continue
        for path in directory.iterdir():
            if path.is_file():
                latest = max(latest, int(path.stat().st_mtime))
    return str(latest)


ASSET_VERSION = _asset_version()

# CompressedStaticFilesStorage (KHÔNG dùng Manifest — manifest sẽ 500 nếu
# thiếu bất kỳ file nào được tham chiếu).
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}
# Tên file static KHÔNG băm (CompressedStaticFilesStorage), nên không được
# cache dài — nếu không, bản build mới sẽ không tới được trình duyệt.
WHITENOISE_MAX_AGE = 0 if DEBUG else 3600


# =============================================================================
# Default Primary Key Field Type
# =============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# Django REST Framework
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}


# =============================================================================
# JWT Configuration (see ADR-004)
# =============================================================================

JWT_SECRET_KEY = os.environ.get('JWT_SECRET_KEY', SECRET_KEY)
JWT_ACCESS_TOKEN_LIFETIME_MINUTES = int(
    os.environ.get('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', 1440)  # 24 hours
)
JWT_REFRESH_TOKEN_LIFETIME_DAYS = int(
    os.environ.get('JWT_REFRESH_TOKEN_LIFETIME_DAYS', 30)  # 30 days
)
JWT_ALGORITHM = 'HS256'


# =============================================================================
# Structured Logging (structlog)
# =============================================================================

import structlog

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': structlog.stdlib.ProcessorFormatter,
            'processor': structlog.dev.ConsoleRenderer() if DEBUG else structlog.processors.JSONRenderer(),
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'chat': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.filter_by_level,
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)


# =============================================================================
# Sentry (Error Tracking)
# =============================================================================

SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        traces_sample_rate=0.1,
        profiles_sample_rate=0.1,
        send_default_pii=False,
    )


# =============================================================================
# Chat Platform Settings
# =============================================================================

# Redis (presence TTL + channel layer)
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

# Presence — Redis TTL state machine (mục 5.7). Tham số chốt cứng.
HEARTBEAT_INTERVAL = 20          # client ping mỗi 20s
PRESENCE_AWAY_TIMEOUT = 45       # 45s không heartbeat → away
PRESENCE_OFFLINE_TIMEOUT = 90    # 90s không heartbeat → offline

# =============================================================================
# Trợ lý AI — TÍNH NĂNG CỘNG THÊM
#
# Không có khoá, khoá sai, hết quota hay tắt cờ -> AI_ASSISTANT_ENABLED = False.
# Khi đó phòng AI bị ẩn hoàn toàn khỏi danh sách và không có đường code nào của
# chat người-người chạm tới lớp AI. App chạy y như chưa từng có tính năng này.
# =============================================================================

AI_API_KEY = os.environ.get('AI_API_KEY', '')
AI_ASSISTANT_ENABLED = (
    os.environ.get('AI_ASSISTANT_ENABLED', 'True').lower() in ('true', '1', 'yes')
    and bool(AI_API_KEY)
)

# Nhà cung cấp mặc định: Google Gemini (có bậc miễn phí).
# Đổi nhà cung cấp = đổi 3 biến này, không đụng phần còn lại của app.
AI_API_URL = os.environ.get(
    'AI_API_URL',
    'https://generativelanguage.googleapis.com/v1beta/models',
)
AI_MODEL = os.environ.get('AI_MODEL', 'gemini-flash-lite-latest')
AI_REQUEST_TIMEOUT = 60          # giây, cả vòng đời một câu trả lời
AI_MAX_OUTPUT_TOKENS = 2048
AI_CONTEXT_MESSAGES = 20         # số tin nhắn gần nhất đưa vào ngữ cảnh
AI_MAX_INPUT_CHARS = 4000        # chặn tin nhắn quá dài trước khi gọi API

AI_BOT_USERNAME = 'cr7-ai'
AI_BOT_DISPLAY_NAME = 'CR7 AI'
AI_ROOM_NAME = 'CR7 AI'

# Xem trước liên kết (mục 7.5)
LINK_PREVIEW_TIMEOUT = 3         # giây, fetch quá thì bỏ qua
LINK_PREVIEW_CACHE_TTL = 86400   # cache Redis 24h
LINK_PREVIEW_MAX_BYTES = 512000  # chỉ đọc 500KB đầu của trang

# Rate limiting
MESSAGE_RATE_LIMIT = 10          # tin nhắn tối đa mỗi giây mỗi kết nối
MESSAGE_MAX_LENGTH = 5000        # ký tự tối đa mỗi tin nhắn

# Vòng đời tin nhắn
MESSAGE_EDIT_WINDOW_SECONDS = 15 * 60   # chỉ sửa được trong 15 phút
OFFLINE_SYNC_LIMIT = 200                # tối đa 200 message mỗi lần sync (mục 5.9)
READ_RECEIPT_THROTTLE_SECONDS = 1.0     # broadcast read receipt 1 lần/giây/phòng

# Email (keep console backend for development)
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
