# Generated by Django 6.1 on 2026-09-06 07:05

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', models.CharField(default='moscow-rain', max_length=32)),
                ('custom_bg', models.ImageField(blank=True, null=True, upload_to=accounts.models.background_upload_path)),
                ('effects_enabled', models.BooleanField(default=True)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('blur_sidebar', models.BooleanField(default=True)),
                ('scrim_strength', models.PositiveSmallIntegerField(default=100)),
                ('sound_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
