# Generated by Django 6.1 on 2026-09-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='blur_sidebar',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='effects_enabled',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='reduced_motion',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='scrim_strength',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='sound_enabled',
        ),
    ]
