# Generated by Django 6.1 on 2026-09-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_is_pinned_message_pinned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_ai',
            field=models.BooleanField(default=False, help_text='Phòng trò chuyện riêng với trợ lý AI, mỗi user một phòng.'),
        ),
    ]
